-- False Friend leaderboard table (NEW)
create table if not exists public.false_friend_scores (
  id bigint generated by default as identity primary key,
  run_id uuid not null unique,
  user_id text not null,
  name text not null,
  total_score integer not null,
  rounds_cleared integer not null,
  created_at timestamptz not null default now()
);

alter table public.false_friend_scores enable row level security;

drop policy if exists "read false friend scores" on public.false_friend_scores;
create policy "read false friend scores"
  on public.false_friend_scores
  for select
  to anon
  using (true);

drop policy if exists "insert false friend scores" on public.false_friend_scores;
create policy "insert false friend scores"
  on public.false_friend_scores
  for insert
  to anon
  with check (
    length(name) between 1 and 20
    and total_score >= 0
    and rounds_cleared >= 0
    and length(user_id) > 0
  );